"""empty message

Revision ID: f3dc9ec7484a
Revises: 63a482dae246
Create Date: 2021-03-16 00:08:21.789326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3dc9ec7484a'
down_revision = '63a482dae246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicalstatus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('diagnosis', sa.String(length=100), nullable=False),
    sa.Column('underlying', sa.String(length=50), nullable=False),
    sa.Column('drug', sa.String(length=50), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=False),
    sa.Column('need_referral', sa.Boolean(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medical_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('height', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('diagnosis', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('underlying', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('drug', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('outcome', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('need_referral', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='medical_status_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='medical_status_pkey')
    )
    op.drop_table('medicalstatus')
    # ### end Alembic commands ###
